letsplay/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from play.routers import router
from rest_framework.urlpatterns import format_suffix_patterns

urlpatterns = [
    url(r'^', include('play.urls')),
    url(r'^api/', include(router.urls)),
    url(r'^admin/', admin.site.urls),
]

urlpatterns = format_suffix_patterns(urlpatterns)

play/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^song/(?P<id>[0-9]+)$', views.song, name='song'),
    url(r'^g/(?P<id>[0-9]+)$', views.showmore, name='showmore'),
    url(r'^search/$', views.search_songs)
]

play/models.py
from __future__ import unicode_literals

from ckeditor.fields import RichTextField
from django.db import models


# Create your models here.


class Genre(models.Model):
    gid = models.IntegerField()
    name = models.CharField(max_length=16)

    def __str__(self):
        return self.name


class Song(models.Model):
    name = models.CharField(max_length=200)
    movie = models.CharField(max_length=200, blank=True)
    lyrics = RichTextField(config_name='awesome_ckeditor', blank=True)
    tabs = RichTextField(config_name='awesome_ckeditor', blank=True)
    chords = RichTextField(config_name='awesome_ckeditor')
    tags = models.CharField(max_length=100)
    genre = models.ForeignKey(Genre)

    def __str__(self):
        return self.name


class LinkType(models.Model):
    source = models.CharField(max_length=20)
    type = models.CharField(max_length=20)

    def __str__(self):
        return self.source


class ImageDetailsForm(models.Model):
    thumbnail = models.CharField(max_length=300)
    image_url = models.CharField(max_length=300)
    image_encoding = models.CharField(max_length=20)
    accent_color = models.CharField(max_length=10)
    name = models.ForeignKey(Song, related_name='imageDetails')


class VideoLinksForm(models.Model):
    link = models.CharField(max_length=300)
    type = models.ForeignKey(LinkType)
    name = models.ForeignKey(Song, related_name='videoLink')

play/views.py
from requests import Response

from django.http import HttpResponse
from django.shortcuts import render, render_to_response
from django.template import loader
from rest_framework import status
from rest_framework.viewsets import ModelViewSet
from rest_framework.pagination import PageNumberPagination

from .serializers import *
from .models import Genre, Song
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


# Create your views here.


def index(request):
    queryset = Genre.objects.all()
    paginator = Paginator(queryset, 10)
    page = request.GET.get('page')
    try:
        queryset = paginator.page(page)
    except PageNotAnInteger:
        queryset = paginator.page(1)
    except EmptyPage:
        queryset = paginator.page(paginator.num_pages)
    context = {
        'genres': queryset,
    }
    return render(request, 'index.html', context)


def song(request, id):
    template = loader.get_template('song.html')
    context = {
        'song': Song.objects.get(id=id)
    }
    return HttpResponse(template.render(context, request))


def showmore(request, id):
    template = loader.get_template('showmore.html')
    context = {
        'g': Genre.objects.get(id=id)
    }
    return HttpResponse(template.render(context, request))


# api/

class StandardResultsSetPagination(PageNumberPagination):
    page_size = 5
    page_size_query_param = 'page_size'
    max_page_size = 100


class GenreList(ModelViewSet):
    queryset = Genre.objects.all()
    serializer_class = GenreSerializer
    pagination_class = StandardResultsSetPagination


class SongList(ModelViewSet):
    queryset = Song.objects.all()
    serializer_class = SongSerializer
    pagination_class = StandardResultsSetPagination

    def retrieve(self, request, pk=None):
        u = request.user
        queryset = Song.objects.filter(user=u, pk=pk)
        if not queryset:
            return Response(status=status.HTTP_400_BAD_REQUEST)
        else:
            serializer = SongSerializer(queryset)
            return Response(serializer.data, status=status.HTTP_200_OK)


class ShowMore(ModelViewSet):
    queryset = Song.objects.all()
    serializer_class = SongSerializer
    pagination_class = StandardResultsSetPagination

    def retrieve(self, request, pk=None):
        u = request.user
        queryset = Song.objects.filter(user=u, pk=pk)
        if not queryset:
            return Response(status=status.HTTP_400_BAD_REQUEST)
        else:
            serializer = SongSerializer(queryset)
            return Response(serializer.data, status=status.HTTP_200_OK)


class SongDetails(ModelViewSet):
    queryset = ImageDetailsForm.objects.all()
    serializer_class = SongLinkList
    pagination_class = StandardResultsSetPagination


def search_songs(request):
    if request.method == 'POST':
        search_text = request.POST['search_text']
    else:
        search_text = ''

    songs = Song.objects.filter(name__contains=search_text)
    return render_to_response('ajax_search.html', {'songs': songs})

templates/ajax_search.html
{% load staticfiles %}
{% if songs.count > 0 %}
    <table>
        <tr>
            {% for song in songs %}
                <td><a href="/song/{{ song.id }}">
                    <div id="search_item_div">
                        <img src="{% static ''|add:song.imageDetails.first.thumbnail %}" width="120px"
                             height="120px" style="border-radius: 5px"/>
                        <div id="song_title" width="120px" height="120px">{{ song.name | truncatechars:25 }}</div>
                    </div>
                </a></td>
                {% if forloop.counter|divisibleby:"4" %}
                    </tr>

                    <tr>
                {% endif %}
            {% endfor %}
            </tr>
    </table>
{% else %}
    <h6 style="color: #777777">No result found!</h6>
{% endif %}

templates/index.html
<html id="html">
{% load staticfiles %}
<head>
    <title>Let's play</title>
    <link href="{% static 'slick/slick.css' %}" rel="stylesheet"/>
    <link href="{% static 'slick/slick-theme.css' %}" rel="stylesheet"/>
    <link href="{% static 'css/normalize.css' %}" rel="stylesheet"/>
    <link href="{% static 'css/skeleton.css' %}" rel="stylesheet"/>
    <link href="{% static 'css/app.css' %}" rel="stylesheet"/>
    <link href="{% static 'css/jquery.dynatable.css' %}" rel="stylesheet"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="//fonts.googleapis.com/css?family=Raleway:400,300,600" rel="stylesheet" type="text/css">
    <link rel="icon" type="image/png" href="{% static 'img/favicon.png' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="{% static 'js/app.js' %}"></script>
    <script src="{% static 'js/jquery.dynatable.js' %}"></script>
    <style type="text/css">

        * {
            box-sizing: border-box;
        }

        .slider {
            width: 50%;
            margin-bottom: 100px;
        }

        .slick-slide {
            margin: 0px 20px;
        }

        .slick-slide img {
            width: 100%;
        }

        .slick-prev:before,
        .slick-next:before {
            color: #ffffff;
        }
    </style>
</head>
<br>
<div id="splashscreen"><h1>Let's Play...</h1>
    <h3 id="tagline">Music opens our heart. Isn't it ?</h3></div>
<div id="header">
    <table width="100%">
        <tr>
            <td class="htd" width="15%">
                <h4><a href="../../#" style="color: #ff4a00">Let's play...</a></h4>
            </td>
            <td class="htd" width="50%" style="text-align: center">
                {% csrf_token %}
                <input id="search" type="text"
                       placeholder="Search for songs, artists, playlists and more"
                       autocomplete="off">
                <div id="search-result">
                </div>
            </td>
            <td class="htd" width="12%" style="text-align: right">
                <img src="{% static 'img/android.png' %}" style="margin-top: -20px" width="30px" height="30px"/>
            </td>
            <td class="htd" style="padding-left: 20px" width="23%">
                <a href="#" id="moreButton"><h6
                        style="color: #ff4a00;  font-family: Arial;text-align: left">Download
                    App</h6></a>
            </td>
        </tr>
    </table>
</div>

<div id="left_side">
    <table style="margin-top: 10px">
        <tr>
            <div class="side_btn active" id="Letsplay">Home</div>
        </tr>
        <tr>
            <div class="side_btn" id="TopPicks">Top Picks</div>
        </tr>
        <tr>
            <div class="side_btn" id="Latest">Latest</div>
        </tr>
        <tr>
            <div class="side_btn" id="NearBy">Near By Institute</div>
        </tr>
        <tr>
            <div class="side_btn" id="SupportUs">Support Us!</div>
        </tr>
    </table>
</div>


<!-- .container is main centered wrapper -->
<div class="container" id="content">
    <!-- columns should be the immediate child of a .row -->
    <div class="row" id="child">
        <div class="twelve column">
            <div class="tab-content">
                <div class="tab-pane active" id="divLetsplay">
                    <ul style="margin-left: 25px">
                        {% for genre in genres %}
                            <div class="genre">
                                <table style="width:100%; margin-bottom: -8px">
                                    <tr>
                                        <th><h3 style="color: #777777">{{ genre.name }}</h3></th>
                                        <th id="moreButton"><a href="/g/{{ genre.id }}" style="color: #ff4a00">More</a>
                                        </th>
                                    </tr>
                                </table>
                                <section class="center slider" style="height: 200px; width: auto;margin-left: -6px;">
                                    {% if genre.song_set.all.count == 0 %}
                                        <h4 style="text-align: center;color: #aaaaaa;">No data available!</h4>
                                    {% endif %}
                                    {% for song in genre.song_set.all %}
                                        {% if forloop.counter <= 10 %}
                                            <a href="/song/{{ song.id }}">
                                                <div id="item_div">

                                                    {% if song.imageDetails.first.thumbnail|length > 0 %}
                                                        <img src="{% static ''|add:song.imageDetails.first.thumbnail %}"
                                                             width="120"
                                                             height="120" style="border-radius: 5px"/>
                                                    {% else %}
                                                        <img src="{% static ''|add:'img/placeholder.jpg' %}" width="120"
                                                             height="120" style="border-radius: 5px"/>
                                                    {% endif %}
                                                    <div id="song_title">{{ song.name | truncatechars:25 }}</div>
                                                </div>
                                            </a>
                                        {% endif %}
                                    {% endfor %}
                                </section>
                            </div>
                        {% endfor %}
                    </ul>

                    <div class="pagination one-fourth column">
            <span class="step-links one-fourth column" style="color: #777777">
        {% if genres.has_previous %}
            <a href="?page={{ genres.previous_page_number }}">previous</a>
        {% endif %}

                <span class="current" style="color: #777777">
            Page {{ genres.number }} of {{ genres.paginator.num_pages }}.
        </span>

                {% if genres.has_next %}
                    <a href="?page={{ genres.next_page_number }}">next</a>
                {% endif %}
    </span>
                    </div>
                    <div id="footer">Under development </br> Email: ashutiwari4@gmail.com</div>
                </div>
                <div class="tab-pane" id="divTopPicks">
                    <p> TopPicks</p>
                </div>
                <div class="tab-pane" id="divLatest">
                    <p> Latest</p>
                </div>
                <div class="tab-pane" id="divNearBy">
                    <p> NearBy</p>
                </div>
                <div class="tab-pane" id="divSupportUs">
                    <p> Support Us!</p>
                </div>
            </div>
        </div>

    </div>

</div>

<script src="https://code.jquery.com/jquery-2.2.0.min.js" type="text/javascript"></script>
<script src="{% static 'slick/slick.js' %}"></script>
<script type="text/javascript">
    $(document).on('ready', function () {
        $(".regular").slick({
            dots: true,
            infinite: true,
            slidesToShow: 3,
            slidesToScroll: 3
        });
        $(".center").slick({
            dots: true,
            infinite: true,
            centerMode: true,
            slidesToShow: 3,
            slidesToScroll: 3
        });
        $(".variable").slick({
            dots: true,
            infinite: true,
            variableWidth: true
        });
    });
    var flag = false;
    var readyStateCheckInterval = setInterval(function () {
        if (document.readyState === "complete" && flag == false) {
            clearInterval(readyStateCheckInterval);
            $('#splashscreen').slideUp(50)
            flag = true;
        }
    }, 0);

</script>

</body>
</html>

templates/showmore.html
<!DOCTYPE html>
<html lang="en" style="overflow: auto">
{% load staticfiles %}
<head>
    <title>Hello-{{ song.name }}</title>
    <link href="{% static 'css/app.css' %}" rel="stylesheet"/>
    <link href="{% static 'css/normalize.css' %}" rel="stylesheet"/>
    <link href="{% static 'css/skeleton.css' %}" rel="stylesheet"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="//fonts.googleapis.com/css?family=Raleway:400,300,600" rel="stylesheet" type="text/css">
    <link rel="icon" type="image/png" href="{% static 'img/favicon.png' %}">
</head>
<body style="background-color: #222222">
<div id="header">
    <h3 style="padding: .5em"><a href="../../#" style="color: #ff4a00">Let's play...</a></h3>
    <h1 id="tagline" style="text-align: center;color: #ff4a00;font-family: monospace">{{ g.name }}</h1>

</div>


<div class="container">
    <!-- columns should be the immediate child of a .row -->
    <div class="row">
        <div class="eleven-one">
            <table>
                <tr>
                    {% for song in g.song_set.all %}
                        {% if genre.song_set.all.count == 0 %}
                            <h4 style="text-align: center;color: #ffffff;">No data available!</h4>
                        {% endif %}
                        <td><a href="/song/{{ song.id }}">
                            <div id="item_div" style="background-color: #333333; border-radius: 5px">
                                {% if song.songdetails.all.count > 0 %}
                                    <img src="{% static ''|add:song.imageDetails.first.thumbnail %}" width="250px"
                                         height="170"
                                         style="border-top-left-radius: 5px; border-top-right-radius: 5px; "/>
                                {% else %}
                                    <img src="{% static 'img/placeholder.jpg' %}" width="250px"
                                         height="170"
                                         style="border-top-left-radius: 5px; border-top-right-radius: 5px; "/>
                                {% endif %}
                                <div id="song_title" style="height: 32px">{{ song.name | truncatechars:30 }}</div>
                            </div>
                        </a></td>
                        {% if forloop.counter|divisibleby:"4" %}
                            </tr>

                            <tr>
                        {% endif %}
                    {% endfor %}
                    </tr>
            </table>
            <div id="footer">Under development </br> Email: ashutiwari4@gmail.com</div>
        </div>
    </div>
</div>


</body>

</html>

templates/song.html
<html style="overflow: auto">
{% load staticfiles %}
<head>
    <title>{{ song.name }}</title>
    <link href="{% static 'css/normalize.css' %}" rel="stylesheet"/>
    <link href="{% static 'css/skeleton.css' %}" rel="stylesheet"/>
    <link href="{% static 'css/app.css' %}" rel="stylesheet"/>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="//fonts.googleapis.com/css?family=Raleway:400,300,600" rel="stylesheet" type="text/css">
    <link rel="icon" type="image/png" href="{% static 'img/favicon.png' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
    <script src="{% static 'js/app.js' %}"></script>
</head>
<body style="background-color: #222222">
<div id="header" style="margin-top: auto">
    <h3 style="padding: .5em"><a href="../../#" style="color: #ff4a00">Let's play...</a></h3>
    <h3 id="tagline" style="text-align: center;color: #ceccbe;font-family: monospace">{{ song.name }}</h3>
</div>


<div class="container">
    <!-- columns should be the immediate child of a .row -->

    <div class="row">
        <div class="eleven">
            <ul class="tab-nav">

                <li>
                    <a class="button active" href="#chords">Chords</a>
                </li>
                <li>
                    <a class="button" href="#tabs">Tabs</a>
                </li>
                <li>
                    <a class="button" href="#lyrics">Lyrics</a>
                </li>
                <li>
                    <a class="button" href="#videos">Videos</a>
                </li>
            </ul>

            <div class="tab-content">
                <div class="tab-pane active" id="chords">
                    <ul>
                        {% if song.chords|length > 0 %}
                            <p>{{ song.chords |safe }}</p>
                        {% else %}
                            <p style="text-align: center">Chords are not available!</p>
                        {% endif %}
                    </ul>
                </div>
                <div class="tab-pane" id="tabs">
                    <ul>
                        {% if song.tabs|length > 0 %}
                            <p>{{ song.tabs | safe }}</p>
                        {% else %}
                            <p style="text-align: center">Tabs is not available!</p>
                        {% endif %}
                    </ul>
                </div>
                <div class="tab-pane" id="lyrics">
                    <ul>
                        {% if song.lyrics|length > 0 %}
                            <p>{{ song.lyrics | safe }}</p>
                        {% else %}
                            <p style="text-align: center">Lyrics is not available!</p>
                        {% endif %}
                    </ul>
                </div>

                <div class="tab-pane" id="videos">
                    {% if "youtube" in song.videoLink.first.link %}
                        <h3 style="color: #ceccbe;font-family: fantasy;padding-top:  1em;"> Watch it on YouTube : </h3>
                        </br>
                        <embed width="854" height="480" src="https://www.youtube.com/v/XGSy3_Czz8k">
                    {% else %}
                        <p style="text-align: center">Video is not available!</p>
                    {% endif %}

                </div>
            </div>
        </div>
    </div>
</div>
<div id="footer">Under development </br> Email: ashutiwari4@gmail.com</div>
</body>

</html>